# Generated by Django 5.0.6 on 2024-05-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_adress', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='company')),
                ('company_email', models.EmailField(max_length=254)),
                ('company_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('DC', 'Design & Creative'), ('DD', 'Design & Developement'), ('SM', 'Sales & Marketing'), ('MA', 'Mobile Application'), ('CT', 'Construction'), ('IT', 'Information Technology'), ('RE', 'Real Estate'), ('CW', 'Content Writter')], max_length=2)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonce.company')),
            ],
        ),
    ]
