# Generated by Django 5.0.6 on 2024-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_job_job_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='job_time',
            field=models.CharField(blank=True, choices=[('TN', 'Temps Plein'), ('TP', 'Temps Partiel'), ('TP', 'Freelance'), ('TP', 'Remote')], max_length=2),
        ),
    ]
